logging:
  level: INFO
  loggers:
    service3: DEBUG
#database:
#  # the name of the JDBC driver, mysql in our case
#  driverClass: com.mysql.jdbc.Driver
#  # the username
#  user: root
#  # the password
#  password:
#  # the JDBC URL; the database is called DWGettingStarted
#  url: jdbc:mysql://localhost:3306/service3
#  properties:
#    charSet: UTF-8